# Generated by Django 4.1.1 on 2022-10-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
