# Generated by Django 4.1.1 on 2022-11-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_movie_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
